name: Your Workflow Name

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Install Java 8 on the agent
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # Compile our application
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      # Publish Unit Test Results
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: target/**/*.xml

      # Install Docker
      - name: Install Docker
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      # Build Docker image
      - name: Docker build
        run: |
          docker build -t image -f Dockerfile .

